# Default values for ignitelab-csuc-slackbot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: ignitelab-csuc-slackbot

service:
  type: NodePort

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
